version: '3'

services:
  integrator-timekeeper:
    image: pdh-integrator-timekeeper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - scheduler-network

networks:
  scheduler-network:
    name: scheduler-network
    external: true